name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.9.1'  # Adjust to your desired Node.js version

      - name: Install dependencies
        run: npm install  # Or use yarn install if you prefer Yarn

      - name: Build and deploy to GitHub Pages
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          # Add more Firebase environment variables as needed
        run: |
          npm run build  # Or use the build command appropriate for your project
          # Additional build commands or scripts

          # Deploy to Firebase using environment variables
          # Replace the following command with your own deployment script
          npm run deploy  # Or the command to deploy to Firebase Hosting
